name: cs7643-final-project-cpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.4
  - numpy=1.21.1
  - matplotlib
  - pyyaml
  - jupyter
  - notebook
  - jupyterlab
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - scikit-learn=0.24.2
